# Static Website Builder Configuration
[site]
name = "Example Website"
nameShort = "ExWeb"
rootUrl = "https://www.example.com"

[build]
sourceDirectory = "./content/"
templateDirectory = "./templates/"
outputDirectory = "./static/"
blacklist = [
    ".",
    "..",
    "__pycache__",
    ".DS_Store",
    "Thumbs.db"
]

[socialMedia] # Optional
# Add any `key:value` pairs for social media links here.
# The link `values` will be available in all templates by the `key` value.
# For example, `substack = "https://mbmcloude.substack.com"` can be accessed in all templates with `{{ substack }}`.
twitter = ""
facebook = ""
instagram = ""
linkedin = ""
youtube = ""
substack = ""

[overrides] # Optional
# Add any `key:value` pairs for adding or overriding template values here.
# Each `value` will be available in all templates by the `key` value.
# For example, `foo = "bar"` can be accessed in all templates with `{{ foo }}`.
